@_default:
    just --list --unsorted

# Install development dependencies
install-dev:
    uv sync --extra dev
    uv run pre-commit install

# Check the codes
check:
    uv run ruff check src tests
    uv run ruff format --check src tests
    uv run pyrefly check
    uv run pyproject-fmt --check pyproject.toml
    uv run rumdl check .

# Format the codes
format:
    uv run ruff format src tests
    uv run pyproject-fmt pyproject.toml
    uv run rumdl check --fix .

# Run tests
test:
    uv run pytest

# Build the project
build:
    uv build

# Publish the project
publish:
    uv publish
